/* Number of total columns/semesters: */
window.semesters = 10;

// Total credits and workload needed for diploma completion by course category
window.categories = [
    { name: "Obrigatórias", totalcredits: 174, totalworkload: 3115, id: 1},
    { name: "Condicionadas", totalcredits: 40, totalworkload: 600, id: 2},
    { name: "Livre Escolha", totalcredits: 8, totalworkload: 120, id: 3},
    { name: "Grupo Humanas", totalcredits: 4, totalworkload: 60, id: 4},
    { name: "Grupo ACE", totalcredits: 0, totalworkload: 405, id: 5},
]

// Order of courses matters: do not swap positions. Append at the end.
window.courses = [
    { name: "Algoritmos e Programação", credits: 5, semester: 1, category: 1, workload: 90}, 
    { name: "Int. a Eng. Comp. e Informação", credits: 2, semester: 1, category: 1, workload: 30},  
    { name: "Circuitos Lógicos", credits: 5, semester: 1, category: 1, workload: 90},  
    { name: "Cálculo I", credits: 6, semester: 1, category: 1, workload: 90},  
    { name: "Física I", credits: 4, semester: 1, category: 1, workload: 60},  
    { name: "Física Experimental I", credits: 1, semester: 1, category: 1, workload: 30},  
    { name: "Linguagens de Programação", credits: 5, semester: 2, category: 1, workload: 90},  
    { name: "Álgebra Linear II", credits: 4, semester: 2, category: 1, workload: 60},  
    { name: "Sistemas Digitais", credits: 5, semester: 2, requirements: [2], category: 1, workload: 90},  
    { name: "Cálculo II", credits: 4, semester: 2, requirements: [3], category: 1, workload: 60},  
    { name: "Física II", credits: 4, semester: 2, requirements: [3, 4], category: 1, workload: 60},  
    { name: "Física Experimental II", credits: 1, semester: 2, requirements: [4, 5], category: 1, workload: 30},  
    { name: "Atividades Acad. Opt. Humanas", credits: 2, semester: 2, category: 4, workload: 30},  
    { name: "Algoritmos e Estrut. de Dados", credits: 5, semester: 3, requirements: [0], category: 1, workload: 75},  
    { name: "Teoria da Computação", credits: 4, semester: 3, category: 1, workload: 60},  
    { name: "Arquitetura de Computadores", credits: 5, semester: 3, category: 1, workload: 75},  
    { name: "Cálculo III", credits: 4, semester: 3, requirements: [9], category: 1, workload: 60},  
    { name: "Física III", credits: 4, semester: 3, requirements: [4, 9], category: 1, workload: 60},  
    { name: "Física Experimental III", credits: 1, semester: 3, requirements: [11], category: 1, workload: 30},  
    { name: "Atividades Acad. Opt. Humanas", credits: 2, semester: 3, category: 4, workload: 30},  
    { name: "Teoria dos Grafos", credits: 4, semester: 4, requirements: [13], category: 1, workload: 60},  
    { name: "Estatística e Mod. Probabilísticos", credits: 4, semester: 4, category: 1, workload: 60},  
    { name: "Computadores e Sociedade", credits: 4, semester: 4, category: 1, workload: 60},  
    { name: "Cálculo IV", credits: 4, semester: 4, requirements: [9], category: 1, workload: 60},  
    { name: "Física IV", credits: 4, semester: 4, requirements: [16, 17], category: 1, workload: 60},  
    { name: "Física Experimental IV", credits: 1, semester: 4, requirements: [18], category: 1, workload: 30},  
    { name: "Banco de Dados", credits: 4, semester: 5, category: 1, workload: 75},  
    { name: "Lógica Matemática", credits: 4, semester: 5, category: 1, workload: 60},  
    { name: "Álg. Linear Computacional", credits: 4, semester: 5, requirements: [7, 16], category: 1, workload: 60},  
    { name: "Redes de Computadores I", credits: 4, semester: 5, category: 1, workload: 75},  
    { name: "Sistemas Operacionais", credits: 5, semester: 5, category: 1, workload: 75},  
    { name: "Química Experimental", credits: 2, semester: 5, category: 1, workload: 60},  
    { name: "Otimização", credits: 4, semester: 6, requirements: [0, 16], category: 1, workload: 60},  
    { name: "Inteligência Computacional", credits: 4, semester: 6, category: 1, workload: 60},  
    { name: "Engenharia de Software", credits: 4, semester: 6, category: 1, workload: 75},  
    { name: "Redes de Computadores II", credits: 4, semester: 6, category: 1, workload: 60},  
    { name: "Telecomunic.", credits: 4, semester: 6, category: 1, workload: 60},  
    { name: "Computação Gráfica", credits: 4, semester: 6, category: 1, workload: 75},  
    { name: "Programação Avançada", credits: 4, semester: 7, requirements: [13, 6], category: 1, workload: 75},  
    { name: "Computação de Alto Desempenho", credits: 3, semester: 7, category: 1, workload: 75},  
    { name: "Sistemas Distribuídos", credits: 4, semester: 7, category: 1, workload: 60}, 
    { name: "Gestão do Conhecimento", credits: 4, semester: 7, category: 1, workload: 60},  
    { name: "Atividades Acad. Optativas", credits: 8, semester: 7, step: 1, category: 2, workload: 120},  
    { name: "Construção de Banco de Dados", credits: 4, semester: 8, requirements: [26], category: 1, workload: 60},  
    { name: "Empreend. I", credits: 4, semester: 8, category: 1, workload: 60},  
    { name: "Qualidade de Software", credits: 4, semester: 8, requirements: [34], category: 1, workload: 60},  
    { name: "Projeto de Graduação", credits: 4, semester: 8, category: 1, workload: 180},  
    { name: "Atividades Acad. Optativas", credits: 8, semester: 8, step: 1, category: 2, workload: 120},  
    { name: "Estágio Obrigatório", credits: 0, semester: 9, category: 1, workload: 160},  
    { name: "Atividades Acad. Optativas", credits: 16, semester: 9, step: 1, category: 2, workload: 240},  
    { name: "Atividades Acad. Optativas", credits: 8, semester: 10, step: 1, category: 2, workload: 120},  
    { name: "Atividades Acad. Livre Escolha", credits: 8, semester: 10, step: 1, category: 3, workload: 120},  
    { name: "Ativ. Compl. Especiais", credits: 0, semester: 10, step: 15, category: 5, workload: 405}, 
	{ name: "Química EE", credits: 4, semester: 4, category: 1, workload: 60}
]
